// === IMÁGENES ===
// Gestión de imágenes: aquí se cargan y se asocian mediante su ID correspondiente en la base de datos
export const imageMap = {
  1: "/Rocket League.jpg",
  2: "/Warframe.jpg",
  3: "/Jujutsu Kaisen.jpg",
  4: "/Hollow Knight.jpg",
  5: "/Shingeki.jpg",
  6: "/minecraft.jpg",
  7: "/boku.jpg",
  8: "/elden.jpg",
  9: "/nanatsu.jpg",
  10:"/stardew.jpg",
  11:"Kimetsu.jpg",
  12:"/cyberpunk.jpg",
  13:"/death note.jpg",
  14:"Red Dead Redemption 2.jpg",
  15:"/one piece.jpg",
  16:"hades.jpg",
  17:"/naruto.jpg",
  18:"/zelda.jpg",
  19:"/fullmetal.jpg",
  20:"/God of War.jpg",
  21:"/Persona 5 Royal.jpg",
  22:"/Hunter x Hunter.jpg",
  23:"/League of Legends.jpg",
  24:"/valorant.jpg",
  25:"/Steins Gate.jpg",
  26:"/The Witcher 3.jpg",
  27:"/Dragon Ball.jpg",
  28:"/celeste.jpg",
  29:"/Portal 2.jpg",
  30:"/evangelion.jpg",
  31:"/Apex Legends.jpg",
  32:"/baldur.jpg",
  33:"/Bloodborne.jpg",
  34:"/Cowboy.jpg",
  35:"/terraria.jpg"
};